title: RadarRoster
description: Transforming Complexity into Clarity, With Data, AI, and Business Strategy
remote_theme: pages-themes/cayman@v0.2.0


plugins:
  - jekyll-remote-theme


show_downloads: false


collections:
  pages:
    output: true
    permalink: /:name/
