title: RadarRoster
description: Data Science & Analytics Services by Daryoosh Dehestani
remote_theme: pages-themes/cayman@v0.2.0


plugins:
  - jekyll-remote-theme


show_downloads: false


collections:
  pages:
    output: true
    permalink: /:name/
